name: Build PR 34 (Error-Free)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Thierbig's PR branch
      uses: actions/checkout@v4
      with:
        repository: thierbig/awesome_wotlk_injection
        ref: main
        submodules: recursive
        
    - name: Setup Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86  # x64 yerine x86 kullan
        
    - name: Fix Detours Interlocked Functions
      run: |
        echo "#define NOWINBASEINTERLOCK" > detours_fix.h
        echo "#include <intrin.h>" >> detours_fix.h
        echo "#pragma intrinsic(_InterlockedExchangeAdd)" >> detours_fix.h
        echo "#pragma intrinsic(_InterlockedCompareExchange)" >> detours_fix.h
        echo "#pragma intrinsic(_InterlockedCompareExchange64)" >> detours_fix.h
        
        # Detours modules.cpp dosyasının başına ekle
        $content = Get-Content "deps\Detours\modules.cpp" -Raw
        $fixedContent = "#include `"../../detours_fix.h`"`n" + $content
        Set-Content "deps\Detours\modules.cpp" $fixedContent
        
    - name: Configure with CMake (x86)
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A Win32 -DCMAKE_CXX_FLAGS="/DNOWINBASEINTERLOCK /D_WIN32_WINNT=0x0601"
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: awesome-wotlk-pr34-error-free
        path: |
          build/Release/*.exe
          build/Release/*.dll
        retention-days: 7
